deployment:
  tasks:
    - echo "Deploy started..."

    # Path public_html (domain utama)
    - export DEPLOYPATH=/home/mrkproje/public_html

    # Copy isi folder public Laravel ke public_html
    - /bin/rsync -av --delete /home/mrkproje/github/main-apps/public/ $DEPLOYPATH/

    # Install dependency composer di folder Laravel
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --working-dir=/home/mrkproje/github/main-apps

    # Jalankan artisan command
    - /usr/local/bin/php /home/mrkproje/github/main-apps/artisan migrate --force
    - /usr/local/bin/php /home/mrkproje/github/main-apps/artisan config:cache
    - /usr/local/bin/php /home/mrkproje/github/main-apps/artisan route:cache
    - /usr/local/bin/php /home/mrkproje/github/main-apps/artisan view:cache

    - echo "Deploy finished..."
